apiVersion: v1
kind: Namespace
metadata:
  name: mc-ns
---
apiVersion: v1
kind: Service
metadata:
  namespace: mc-ns
  name: mc-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mc-stress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mc-ns
  labels:
    app: mc-stress
  name: mc-web
spec:
  selector:
    matchLabels:
      app: mc-stress
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mc-stress
    spec:
      containers:
      - image: k8s.gcr.io/hpa-example
        name: stresser
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 0.2
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mc-hpa
  namespace: mc-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mc-web
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 50